rest/stargate.go
rest/util.go

only count all when `pagination.count_total` is set

💥 Disable count total in stargate txs endpoint by default

---

poller/poller.go

Prevent catch up fail would cause sync backt to zero when there is not much transactions in testnet

✨ Flush transactions to db per height period

---

rest/height.go
rest/router.go

✨ Add endpoint latest/height

---

rest/router.go

♻️ Update height endpoint

---

rest/router.go

♻️ Add withConn

---

rest/amino.go

Now in legacy amino `/txs` endpoint, total number of txs won't be counted and result in `0` unless `count_total=1` is specified in the query.
`total_count` will be `0` in the response.

Don't count total number of txs by default in legacy `/txs` endpoint

---

db/nft.go
db/types.go
rest/nft.go

✨ Allow no query in creator and collector api

✨ Allow no query in creator and collector api

---

db/nft.go
db/types.go

✨ Add ignore to and from list in event

✨ Add ignore to and from list in event

---

db/nft.go

May have the same issue in other APIs

Fix duplicated collectors across paginations in collector API

---

db/nft.go
db/nft_test.go
db/types.go
rest/nft.go
rest/router.go
test/testsetup.go

(Surprisingly) acceptable performance

✨ Add collector in creator top K query

---

cmd/migrate/migrate.go
cmd/migrate/nft_event_memo.go
db/extract.go
db/nft.go
db/schema/parallel/nft_event_memo.go
db/schema/v012.sql
extractor/event_extractor.go
extractor/event_extractor_test.go
extractor/marketplace_test.go
test/testsetup.go

by embedding `memo` into `nft_event`

Optimize NFT event performance

---

Makefile

🔨 Fix Docker build arg ordering

---

db/nft.go
db/nft_test.go
db/types.go
rest/nft.go

`Involver` = `Sender` OR `Receiver` OR `Creator`

✨ Add `involver` in NFT event query

---

db/stats.go
db/stats_test.go
db/types.go
rest/stats.go

Not sure if performance is an issue, if so may use materialized view and refresh regularly in poller

✨ Count trade stats for all action types

---

db/iscn_test.go
db/marketplace_test.go
db/nft_test.go
db/stats_test.go
extractor/event_extractor_test.go
extractor/extractor_test.go
extractor/iscn_test.go
extractor/marketplace_test.go
extractor/nft_test.go
rest/amino_test.go
rest/iscn_test.go
rest/marketplace_test.go
rest/stargate_test.go
test/testsetup.go
utils/addr_test.go
utils/sanitize_test.go
utils/utils_test.go

Simply replace all handwritten `if ... t.Errorf(...)` to `require.XXX(...)` so it's less clumsy and more declarative

✅ Use testify/require in tests

---

db/db.go
rest/stargate.go

This allows monitoring last n txs based on indexer endpoint without Postgres access

✨ Allow querying txs without events or height

---

db/extract.go
extractor/marketplace.go

https://github.com/likecoin/likecoin-chain/blob/master/x/likenft/keeper/msg_server_listing.go#L41
https://github.com/likecoin/likecoin-chain/blob/master/x/likenft/keeper/msg_server_listing.go#L142
chain prunes invalid entry on create and delete listing msg

🐛 Invalid listing should be deleted for `MsgCreateListing` and `MsgDeleteListing`

---

db/nft.go

Use CTE to force query planner to do scans on `nft` and `nft_events` first.
But for the long run maybe we need to separate this API to several more specific APIs, so there are less combinations and we can optimize / control the query plans for different kinds of use cases more specifically.

⚡️ Optimize ranking query performance

---

db/nft.go
db/nft_test.go
db/types.go

- Deprecate unused `expand` qs fields 
- Improve performance

[TAS-153] ⚡️ Replace subquery with join clause for better performance

---

db/stats.go
db/stats_test.go
rest/router.go
rest/stats.go

To replace an inaccurate and slow /txs query with iscn module search that we were using

✨ Add iscn record count api
